ibm_cloud_fail_over/__init__.py,sha256=wkw-L_MFuf-3LhHXmWNoVwVUUJlgTdO3AB6csgmjCQo,215
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=cpsHngAlge2dSCySdkvqkwIgI3oYS02_1Q9BZSF_ew8,25011
ibm_cloud_fail_over-1.0.7.dist-info/METADATA,sha256=ENmXAPKY3eE-aM75qdrHSzd3M0RIPt1mog9rQzp74Yk,7065
ibm_cloud_fail_over-1.0.7.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.7.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.7.dist-info/RECORD,,
